### ISSUE TITLE
Backup stops at the same point and does not continue

### ISSUE THREAD

**Issue by RasaKh** [fabianonline/telegram_backup#10]
Well I guess you could call it a bug :) !
I've tried many times and it's the same : Download stops at 253000 messages
I even deleted the sql file so it would start from the very beginning but it's the same
https://drive.google.com/open?id=0B3vesUpZ3j58Wmx0RDQ3X0FBUVE

**Comment by fabianonline** [comment]
That's definitely a bug. I didn't know you could get TLDocuments without TLDocumentAttributes... It will be fixed in 1.0.5, which should be finished in a few days.

**Comment by RasaKh** [comment]
Ok thanks
