### ISSUE TITLE
Charts not working

### ISSUE THREAD

**Issue by ssdd28561** [fabianonline/telegram_backup#13]
Exported files have this at the end: 
`<script type="text/javascript" src="//code.jquery.com/jquery-1.9.1.js"></script>`

and the script is not loaded (so there are no any pie charts etc).

If you change it to 
`<script type="text/javascript" src="https://code.jquery.com/jquery-1.9.1.js"></script>`
everything will work.

**Comment by fabianonline** [comment]
Urk. My bad. It works as long as you access the HTML files via http or https instead of as local files.
Will be fixed in 1.0.6.
