### ISSUE TITLE
One message is redownloaded every time

### ISSUE THREAD

**Issue by bodqhrohro** [fabianonline/telegram_backup#130]
On every run, I get the message:
```
Downloading 1 messages from channel Інтертекст
...1 done.
```
Even though there were no new posts on this channel (https://t.me/intertextTV) for a long time.

**Comment by fabianonline** [comment]
This happens everytime the last message in a group or channel was a "administrative message" like "... joined your channel" or something.

This is a bit annoying, but it doesn't mean that any important messages are skipped.
