### ISSUE TITLE
Chats are not exported into html

### ISSUE THREAD

**Issue by ssdd28561** [fabianonline/telegram_backup#16]
since 1.0.5-test.1 and 1.0.5-test.2

I have older files for chats but they are not updated, and they haven't exported from the scratch when i deleted them. 

The messages to bots and users are exported fine

**Comment by fabianonline** [comment]
Hm. It's working fine for me...

Can you please grab 1.0.5-test.4 from https://github.com/fabianonline/telegram_backup/releases/tag/1.0.5-test.4, run it with `--export html` and `--trace` and check that the files you expect to be created are listed in the output?

**Comment by ssdd28561** [comment]
http://i.imgur.com/D0xBojR.png

Just stops at 
`DEBUG HTMLExporter.export                : Generating chat pages`

**Comment by fabianonline** [comment]
Are there (even non-functioning) links to the chats on the main page of the export?

**Comment by ssdd28561** [comment]
Yes, there are links on "index" page, but they lead to nowhere (because files with those chats were not created)

**Comment by fabianonline** [comment]
I'm having troubles reproducing this bug... Could you please grab 1.0.5-test.5 from https://github.com/fabianonline/telegram_backup/releases/tag/1.0.5-test.5, run it with `--trace` and report back on the output?

**Comment by luckydonald** [comment]
Are these files very old, and not available to any other client as well?

**Comment by ssdd28561** [comment]
Deleted all the files, tried 1.0.5-test.5, can't reproduce the bug 👍
