### ISSUE TITLE
Backup channels as well

### ISSUE THREAD

**Issue by fabianonline** [fabianonline/telegram_backup#18]

**Comment by nelo686** [comment]
Hi @fabianonline, did you add this feature to 1.0.6? How we should use it? I would like to have it.

**Comment by fabianonline** [comment]
Duplicate (cause channels and supergroups are handled quite similarly) of #21. Closing this.

Just a quick heads-up: I'm currently actively working on this feature and expect a first test release to be available in just a few days.
