### ISSUE TITLE
Supergroup backup

### ISSUE THREAD

**Issue by Millik42** [fabianonline/telegram_backup#21]
It would be great to add supergroup backup.

**Comment by lukeroge** [comment]
Any news on this?

**Comment by fabianonline** [comment]
Sorry, time is short at the moment. But I will eventually come around to this feature. But it might just take a few weeks... :-/

**Comment by Hypfer** [comment]
So what's the status on this essential feature?

**Comment by fabianonline** [comment]
Not much news - my time shortness is getting better now, but there's some other stuff that's a lot more important to me than this feature. But it's not forgotten. ;-)

**Comment by Hypfer** [comment]
https://github.com/Hypfer/telegram_backup now downloads supergroups as well.
Could use some cleanup, though so no PR yet. Some stuff isn't finished. Lots of copy&paste.

**Comment by Millik42** [comment]
Nice. Hope to see this feature in near releases

**Comment by fabianonline** [comment]
I'm currently working on this.
