### ISSUE TITLE
GIF backuped as mp4

### ISSUE THREAD

**Issue by Alex131089** [fabianonline/telegram_backup#22]
Hi, 

just finished my first backup, and I noticed that (edit: some) gif are being backuped as mp4. Animated GIFs take less space, but I would be great to have the original file too.
Can you fetch the original file, and maybe as an option, fetch the converted mp4 too ?

Anyway, thanks for this tool !

**Comment by Alex131089** [comment]
Example file : http://alex.twb.fr/epita/081209014009489852852137.gif (4 MB, retreived as 170 KB mp4, but retreivable as gif with TDesktop)
Trace entry for the file : 
```00:49:58 TRACE DownloadManager._downloadMedia     : message 166883, …Document, DocumentFileManager, non-empty, downloaded```

**Comment by tjhorner** [comment]
The original GIF is not stored on the Telegram servers, so this would be impossible.

**Comment by Alex131089** [comment]
It appears that TDesktop keeps a link to the sent file, so the sender can find it back ; useless issue then, sorry.
Thanks for the tool still, worked perfectly 👍
