### ISSUE TITLE
Not an issue : need to know how did you get version

### ISSUE THREAD

**Issue by amoghsa** [fabianonline/telegram_backup#45]
Hi,

May I know how did you get string "666a81ef9d6707f117a3fecc2d21c91d51c7d075" for kotlogram version?  Did you generate it, I actually tried to convert this to maven for my curiosity, but I was not able to? As kotlogram dependency in gradle was mentioned in string which is not available in any maven repo, I tried.

Thanks,
Amogh.

**Comment by fabianonline** [comment]
That hash is pointing to an explizit commit in the git repository of kotlogram.

**Comment by amoghsa** [comment]
Thanks !!
