### ISSUE TITLE
Backup Of Channels And Supergroups

### ISSUE THREAD

**Issue by amirmsz** [fabianonline/telegram_backup#57]
Hi
How Can I Backup Of My Channels And Supergroups?
Please Help

**Comment by Millik42** [comment]
supergroups can be backuped with this version https://github.com/Hypfer/telegram_backup

**Comment by amirmsz** [comment]
Thanks A Lot!! But Can You Send The Link Of The Download, Please?

**Comment by Millik42** [comment]
you have to compile jar file by your own

**Comment by amirmsz** [comment]
Holy Shit!!!
But How Can I Compile Jar File?

**Comment by amirmsz** [comment]
Please HELP ME!!
I Can't Compile!!
If You Can Please Learn To ME!!

**Comment by fabianonline** [comment]
Duplicate (cause channels and supergroups are handled quite similarly) of #21. Closing this.

Just a quick heads-up: I'm currently actively working on this feature and expect a first test release to be available in just a few days.
