### ISSUE TITLE
Supergroups are always recognized as Channels (and because of that sender_id is always empty in supergroup messages)

### ISSUE THREAD

**Issue by CTassisF** [fabianonline/telegram_backup#69]
Following the [v1.1.0](https://github.com/fabianonline/telegram_backup/tree/1.1.0) update I noticed that _supergroups_ are always recognized as _channels_ and because of that the `sender_id` attribute of the table `messages` is always empty when that message is from a _supergroup_.

According to the following code, it was supposed to be empty only when that message comes from a _channel_:
https://github.com/fabianonline/telegram_backup/blob/2321fa11eec72ec9d3d7d3e8fd2b774f6c1f4c84/src/main/java/de/fabianonline/telegram_backup/Database.java#L216-L221
It may still be possible to get the `sender_id` from _channels_ though when "sign messages" is enabled for that _channel_.

I guess this is happening because _supergroups_ are in fact _channels_ with the `megagroup` attribute set to `true`.

**Comment by fabianonline** [comment]
Thanks. Fixed this in code. The fix will be included in the next release.

**Comment by CTassisF** [comment]
Thanks!
By the way, I think the data saved in the `chats` table still saves __supergroups__ as __channels__.
