### ISSUE TITLE
[FEATURE REQUEST] Make the download of common groups also switchable.

### ISSUE THREAD

**Issue by Millik42** [fabianonline/telegram_backup#72]
Now we have switches to select either download channels or/and SGs or not.
Is it possible to make same switch for common groups? So I can download only necessary type of chat.

**Comment by fabianonline** [comment]
No, that's not possible, since I have to download all messages before being able to determine if they are from a normal chat or a group. But there will be a switch
for downloading media files from normal groups as well.
