### ISSUE TITLE
Thank you and comments/suggestions

### ISSUE THREAD

**Issue by PaulNerd** [fabianonline/telegram_backup#76]
First of all, thanks a lot for your hard work! your piece of software works a charm and did in a matter of hours what I could not do with anything else, and in a very neat way.

A couple of considerations:

1. my "files" folder has next to 8k files in it... maybe it could be better to create subfolders based on file type ("documents", "pictures", "videos", "audio"), as it's already the case for "dialogs" and "stickers", and only leave the index.html file in the main "files" folder.
I know this would bloat the html files (six to ten more characters for each link, including the slash), but it would make for a neater file structure.

2. one of my chats produced a 60+ MB html file... Firefox is still handling that one ok, so no concerns at present... maybe one could, in the future, add an option for spanning html report files. Not a priority, though.

Thanks again and best regards.

**Comment by simplyQQ** [comment]
These are great ideas! I would also like to add one more:

3. Ability to filter export to HTML by chat/contact/etc. Would be very very good way to manage your history backups.

**Comment by Rapti** [comment]
Perhaps a pagination would solve #2. That should be optional though as it makes searching messages using CTRL+F pretty much impossible.

**Comment by fabianonline** [comment]
Yes, pagination is going to help against huge HTML files. It is basically implemented; I just have to add a few more little things to make the new version ready to release.

**Comment by fabianonline** [comment]
Number 2 (pagination) was added in 1.1.0.
Number 1 (folders for files) is being discussed in #56. So I'll close this issue.
