### ISSUE TITLE
Support for cyrillic characters, especially in export?

### ISSUE THREAD

**Issue by ssdd28561** [fabianonline/telegram_backup#8]
Well, basically, all my messages are question marks:)

**Comment by fabianonline** [comment]
Hm. If looks fine to me.

Which OS are you using? Which browser? Did you try to use another browser? Chrome & Firefox work for me.

**Comment by ssdd28561** [comment]
Looks like this http://i.imgur.com/j7ZazRI.png in both chrome and opera? w10x64 
🤔

**Comment by fabianonline** [comment]
Looking into this. My best guess is that there's something strange going on with the file encoding at your side. Can you please grab 1.0.5-test.1 from here https://github.com/fabianonline/telegram_backup/releases/tag/1.0.5-test.1, run it with `--test 2` and then paste the output here? (Please remember to mask your phone number.) The output could be very helpful in solving this bug.

**Comment by ssdd28561** [comment]
> Telegram_Backup version 1.0.5-dirty, Copyright (C) 2016 Fabian Schlenz
> 
> Telegram_Backup comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
> welcome to redistribute it under certain conditions; run it with '--license' for details.
> 
> Base directory for files: D:\TEMP\Telegram_Backup\
> Default Charset:   windows-1251
> file.encoding:     Cp1251
> Opening database...
> Database is ready.
> Database encoding: UTF-8

**Comment by ssdd28561** [comment]
I replaced 
`<meta charset="UTF-8">`
with this
`<meta charset="windows-1251">`

and everything is readable now. Can we have an option for default encoding?

**Comment by fabianonline** [comment]
I'd rather have a solution in place that doesn't need the user being informed about charsets and stuff. I'll tackle this bug this evening.

**Comment by fabianonline** [comment]
Could you please grab 1.0.5-test.2 from https://github.com/fabianonline/telegram_backup/releases/tag/1.0.5-test.2 and try the export with that version?

**Comment by ssdd28561** [comment]
Everything works fine, including emojis, great!

**Comment by fabianonline** [comment]
Great to hear that.
