### ISSUE TITLE
Switch to TDLib ?

### ISSUE THREAD

**Issue by Alex131089** [fabianonline/telegram_backup#85]
Hello, 

I'm sure you're aware there's now an official lib to interact with Telegram API, is it interesting to use it / do you plan to use it ?

https://telegram.org/blog/tdlib
https://github.com/tdlib/td

**Comment by fabianonline** [comment]
Yes, I'm aware of this. But thanks for pointing this out anyways.

But right now I don't see a reason to change libs. While it may be nice to be working with an official library, the tool wouldn't gain any new features and it would take a huge lot of work to implement TDlib.
