### ISSUE TITLE
Some media items don't get downloaded, get ommitted

### ISSUE THREAD

**Issue by shiksb** [fabianonline/telegram_backup#86]
Here's a picture of what happens: 
<img width="938" alt="screen shot 2018-02-11 at 1 07 16 pm" src="https://user-images.githubusercontent.com/25540727/36076635-cd9fe924-0f2c-11e8-930e-26e3d2d3dd72.png">

It tries downloading the files, and throws the ClosedChannelException (which is fine), but after a few attempts it just skips the file as 'x'. The partial download is present in the download folder. This didn't happen earlier.

**Comment by fabianonline** [comment]
Unfortunately, that stuff is happening within the telegram library I'm using. Just ignore that error - when you run telegram_backup the next time, it will find the partial downloads and continue them.
