### ISSUE TITLE
Support local phone db

### ISSUE THREAD

**Issue by mirh** [fabianonline/telegram_backup#9]
I'm referring to `/data/data/org.telegram.messenger/files/cache4.db`
I think it could be a cool "starting point" to lower required server activity. 
I heard it's not plain sqlite though, and that it would need to be parsed with the relative [java](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/java/org/telegram/tgnet/TLRPC.java) lib.

**Comment by fabianonline** [comment]
Spent some time looking into this. But it would be a lot of work just for a few people. It looks like the cache4.db doesn't even contain all the data I need for my tool to work. And even if it did, the format is all wrong...

Downloading the messages is relatively quick with batches of 100 messages. The cache4.db will only contain the messages your smartphone "has seen". 

So... sorry, but I won't implement this. :-(

**Comment by mirh** [comment]
> Downloading the messages is relatively quick with batches of 100 messages. The cache4.db will only contain the messages your smartphone "has seen". 

Yes, but just for the records, my db must have something like 4-5 millions messages, considering it goes back up to march 2015, and normally 1million messages limit already stops me this April. 

But.. kay.

**Comment by fabianonline** [comment]
*That* is a good reason to support this. :D

I've looked some more into this. The cache4.db is a regular sqlite3 database, but the messages in there are in some binary representation. But it's not the same binary representation I'm using. (That would be too easy, I guess.) According to the source code, they come from the TGNet library - which is a huge problem, because that uses binary JNI objects which are only available for mobile processors (ARM and something I've forgotten). So... I can't do anything.

By the way: My cache4.db doesn't seem to be complete. There are about 500 messages missing. Could you have a look at yours?

Something like
```
adb shell
su
sqlite3 /data/data/org.telegram.messenger/files/cache4.db
SELECT COUNT(*) FROM messages;
```
should be enough. But it won't work if your phone isn't rooted.

**Comment by mirh** [comment]
It returns `2213984`
Uh, and just for the records, it's 600MB big :*

**Comment by fabianonline** [comment]
Hm. It might be possible after all. At least for all messages with the current API layer...

Could you please run the following command and post the output here?

```
select substr(hex(data), 0, 8) as type, count(mid) from messages group by type;
```

(same commands as above, just the last line changed). The command might take some time to run. The output will only contain the message types (with API layer within them) and their count. No personal stuff. This is for me to see how much of your database could be useful. I'll reopen this for now.

**Comment by mirh** [comment]
07966BC|6499
136CA65|426434
54DEE58|9
5CE192C|319849
5FE49BC|1455651
F6A1199|5520
F855555|18
F955555|4

**Comment by fabianonline** [comment]
What I found during a quick research session:

TLMessageService v45 |6499
TLMessageEmpty v53 | 9
TLMessage v45 | 319849
TLMessage v53 | 1455651
TLMessageService v53 | 5520

What I couldn't find right now (will continue looking tomorrow):
136CA65 | 426434
F855555 | 18
F955555 | 4

**Comment by fabianonline** [comment]
I've put a test version at https://transfer.sh/WwcyR/telegram-backup.jar

Could you please download your cache4.db to your computer and then run the version from above with `--test 1`? The cache4.db has to be in your working directory.

The new version will have a look at the data inside cache4.db and try to parse it. It won't do anything with it except showing short stats on how many messages are usable and how many are not.

**Comment by mirh** [comment]
Success:                 2213984
Unsupported constructor: 754243

**Comment by fabianonline** [comment]
Since my spare time is pretty limited and this is a pretty unique request requiring quite a lot of work, I'm going to skip this one. Sorry. :-(
